version: "2.1"
services:
  oc-ui:
    container_name: oc-ui
    image: oc-ui:latest
    restart: always
    build: ./oc-ui
    ports:
      - "80:80"
    networks:
      - oc-network

networks:
  oc-network:
    driver: bridge
